feat: LDP-2492: Add webform support with proxy
drunomics/lupus-decoupled-nuxt3-demo pull request #31
Opened 2024-06-13 15:31 UTC by vloss3

2024-06-13 15:32 UTC, vloss3 commented on server/routes/form-handler.ts
> +})
this can be moved to nuxtjs-drupal-ce

2024-06-15 04:41 UTC, fago requested changes

2024-06-15 04:41 UTC, fago commented on components/global/DrupalForm.vue
> +  <form vue-enabled :formId="formId" :method="method" v-bind="attributes" @submit.prevent="submitForm">
this submits the form with JS. we want form-submissions to work progressively, thus we need to make it work without JS first.

2024-06-15 04:44 UTC, fago commented
* webform is not the goal
* js-enabled form submissions is not the goal
see https://www.drupal.org/project/lupus_decoupled/issues/3336148#comment-15640993

2024-08-30 05:49 UTC, merged