feat: LDP-2673: Make compatible with Drupal CMS blog recipe
drunomics/lupus-decoupled-nuxt3-demo pull request #65
Opened 2024-12-23 12:10 UTC by vloss3

2024-12-23 12:51 UTC, ivangrozni approved these changes

2025-01-19 05:07 UTC, fago requested changes

2025-01-19 05:07 UTC, fago commented on components/global/drupal-layout.vue
> +      <component :is="renderCustomElements(element)" v-for="(element, index) in content" :key="index" />
I think this would be fixed by https://github.com/drunomics/nuxtjs-drupal-ce/pull/299/files

2025-01-19 05:07 UTC, fago commented on components/global/node-blog-teaser.vue
> +    <h2 v-if="title" class="mb-2 text-3xl font-semibold">{{ title }}</h2>
I think the naked starter should stick with defaults as we have it in nuxtjs-drupal-ce

we need to think on how to support drupal-cms best. maybe create a separate starter? or ship components with our recipes and copy it over to the frontend when installing the recipe?

2025-01-25 03:39 UTC, fago commented
let's clarify at https://www.drupal.org/project/lupus_decoupled/issues/3501620#comment-15954120 how to do this!

2025-01-25 03:39 UTC, closed without merging